services:
  web:
    build:
      context: .
      args:
        - DISPLAY_VERSION=docker-compose
    ports:
      - "8000:8000"
    environment:
      - DB_LOCATION=/home
    volumes:
      - .:/home:rw
